version: 8
jobs:
- name: build
  steps:
  - !CheckoutStep
    name: check out
    cloneCredential: !DefaultCredential {}
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: build
    image: docker:19.03.5
    commands:
    - echo "start build @project_name@ image"
    - if [ $(docker ps -a | grep -c "@project_name@") -gt 0 ]
    - 'then '
    - "\tdocker stop @project_name@;"
    - '    docker rm @project_name@;'
    - '    docker rmi lain/@project_name@;'
    - fi;
    - docker build -t lain/@project_name@ .
    - docker run -d -p 8889:8889 --net lainnet --name @project_name@ --restart=always
      -v /home/ubuntu/hana/imageCache:/app/imageCache lain/@project_name@
    - echo "end build @project_name@ image"
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 250m
  memoryRequirement: 128m
  timeout: 3600
